import type { MCPServerForm as MCPServerFormModel, SkillForm as SkillFormModel, ToolForm as ToolFormModel } from "../pages/library/capabilityForms";
import { StringChipList } from "./StringChipList";

interface BaseProps<T> { form: T; disabled?: boolean; isCreate: boolean; onChange: <K extends keyof T>(key: K, value: T[K]) => void; }

export function SkillForm({ form, disabled, isCreate, onChange }: BaseProps<SkillFormModel>) {
  return <div className="guided-form"><section className="explain-panel"><h3 className="explain-title">One Markdown-only skill package</h3><p className="explain-body">Exactly one <span className="mono">SKILL.md</span> plus optional Markdown references. Scripts and binary assets belong in a separately selected AgentTool.</p></section>
    <label className="field"><span className="label">Name</span><input className="input mono" value={form.name} disabled={!isCreate || disabled} onChange={(e) => onChange("name", e.target.value)} /></label>
    <label className="field"><span className="label">Description</span><textarea className="textarea" value={form.description} disabled={disabled} onChange={(e) => onChange("description", e.target.value)} /></label>
    <label className="field"><span className="label">Source</span><select className="select" value={form.mode} disabled={disabled} onChange={(e) => onChange("mode", e.target.value as SkillFormModel["mode"])}><option value="inline">Inline Markdown</option><option value="github">Pinned GitHub commit</option></select></label>
    {form.mode === "inline" ? <><label className="field"><span className="label">SKILL.md</span><textarea className="textarea textarea-spec" value={form.skillMD} disabled={disabled} spellCheck={false} onChange={(e) => onChange("skillMD", e.target.value)} /></label><label className="field"><span className="label">Markdown references (JSON)</span><textarea className="textarea textarea-spec" value={form.referencesJSON} disabled={disabled} spellCheck={false} onChange={(e) => onChange("referencesJSON", e.target.value)} /><p className="field-help">Array of {`{"path":"references/example.md","content":"# …"}`}. Only safe relative .md paths are accepted.</p></label></> : <><div className="field-row"><label className="field"><span className="label">Repository</span><input className="input mono" value={form.repository} disabled={disabled} placeholder="owner/repository" onChange={(e) => onChange("repository", e.target.value)} /></label><label className="field"><span className="label">Full commit SHA</span><input className="input mono" value={form.ref} disabled={disabled} onChange={(e) => onChange("ref", e.target.value)} /></label></div><label className="field"><span className="label">SKILL.md path</span><input className="input mono" value={form.path} disabled={disabled} onChange={(e) => onChange("path", e.target.value)} /></label><StringChipList label="Markdown reference paths" value={form.referencePaths} disabled={disabled} onChange={(next) => onChange("referencePaths", next)} /><label className="field"><span className="label">GitHub API base URL (optional)</span><input className="input mono" value={form.apiBaseURL} disabled={disabled} placeholder="https://api.github.com" onChange={(e) => onChange("apiBaseURL", e.target.value)} /></label><div className="banner banner-info">This editor records an immutable source reference. It does not browse private repositories, select credentials, or import scripts/assets.</div></>}
  </div>;
}

export function ToolForm({ form, disabled, isCreate, onChange }: BaseProps<ToolFormModel>) {
  return <div className="guided-form"><div className="banner banner-warn"><strong>Code-execution authority.</strong> Every AgentTool supplies executable code to consuming AgentRuns. Review sources, digests, scripts, and verify argv.</div>
    <label className="field"><span className="label">Name</span><input className="input mono" value={form.name} disabled={!isCreate || disabled} onChange={(e) => onChange("name", e.target.value)} /></label><label className="field"><span className="label">Description</span><textarea className="textarea" value={form.description} disabled={disabled} onChange={(e) => onChange("description", e.target.value)} /></label>
    <div className="field-row"><label className="field"><span className="label">Published command name</span><input className="input mono" value={form.executableName} disabled={disabled} onChange={(e) => onChange("executableName", e.target.value)} /></label><label className="field"><span className="label">Relative executable path</span><input className="input mono" value={form.executablePath} disabled={disabled} onChange={(e) => onChange("executablePath", e.target.value)} /></label></div>
    <label className="field"><span className="label">Acquisition</span><select className="select" value={form.mode} disabled={disabled} onChange={(e) => onChange("mode", e.target.value as ToolFormModel["mode"])}><option value="httpArtifact">HTTPS artifacts</option><option value="ociArtifact">Digest-pinned OCI artifacts</option><option value="inlineScript">Inline executable script</option><option value="setupScript">Unrestricted setup script</option></select></label>
    {form.mode === "inlineScript" ? <><StringChipList label="Interpreter argv" value={form.interpreter} disabled={disabled} onChange={(next) => onChange("interpreter", next)} /><label className="field"><span className="label">Script</span><textarea className="textarea textarea-spec" value={form.script} disabled={disabled} spellCheck={false} onChange={(e) => onChange("script", e.target.value)} /></label></> : form.mode === "setupScript" ? <label className="field"><span className="label">Setup script</span><textarea className="textarea textarea-spec" value={form.setupScript} disabled={disabled} spellCheck={false} onChange={(e) => onChange("setupScript", e.target.value)} /><p className="field-help">Unrestricted compatibility escape hatch; it runs with the consuming Job’s authority.</p></label> : <label className="field"><span className="label">Platform artifacts (JSON)</span><textarea className="textarea textarea-spec" value={form.artifactsJSON} disabled={disabled} spellCheck={false} onChange={(e) => onChange("artifactsJSON", e.target.value)} /><p className="field-help">Use CRD-shaped entries with platform plus HTTPS/SHA-256/format or OCI digest/executable path.</p></label>}
    <StringChipList label="Verify command argv" value={form.verifyCommand} disabled={disabled} onChange={(next) => onChange("verifyCommand", next)} />
  </div>;
}

export function MCPServerForm({ form, disabled, isCreate, onChange }: BaseProps<MCPServerFormModel>) {
  return <div className="guided-form"><section className="explain-panel"><h3 className="explain-title">Secret-free MCP contract</h3><p className="explain-body">Credentials remain environment-backed in the harness. This resource cannot select Secrets. A stdio executable must be selected independently as an AgentTool or already exist in the harness image.</p></section>
    <label className="field"><span className="label">Name</span><input className="input mono" value={form.name} disabled={!isCreate || disabled} onChange={(e) => onChange("name", e.target.value)} /></label><label className="field"><span className="label">Description</span><textarea className="textarea" value={form.description} disabled={disabled} onChange={(e) => onChange("description", e.target.value)} /></label>
    <label className="field"><span className="label">Transport</span><select className="select" value={form.mode} disabled={disabled} onChange={(e) => onChange("mode", e.target.value as MCPServerFormModel["mode"])}><option value="stdio">stdio</option><option value="streamableHTTP">Streamable HTTP</option></select></label>
    {form.mode === "stdio" ? <StringChipList label="Command argv" value={form.command} disabled={disabled} onChange={(next) => onChange("command", next)} /> : <><label className="field"><span className="label">HTTPS endpoint</span><input className="input mono" value={form.endpoint} disabled={disabled} placeholder="https://mcp.example.com/mcp" onChange={(e) => onChange("endpoint", e.target.value)} /></label><label className="field"><span className="label">Environment-backed headers (JSON)</span><textarea className="textarea textarea-spec" value={form.headersJSON} disabled={disabled} spellCheck={false} onChange={(e) => onChange("headersJSON", e.target.value)} /><p className="field-help">Example: {`[{"name":"Authorization","envVar":"MCP_AUTHORIZATION"}]`}. Header values never enter this CR.</p></label></>}
    <StringChipList label="Required environment-variable names" value={form.requiredEnv} disabled={disabled} onChange={(next) => onChange("requiredEnv", next)} /><StringChipList label="MCP tool allowlist" value={form.toolAllowlist} disabled={disabled} onChange={(next) => onChange("toolAllowlist", next)} />
  </div>;
}
