//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdverseSituation) DeepCopyInto(out *AdverseSituation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdverseSituation.
func (in *AdverseSituation) DeepCopy() *AdverseSituation {
	if in == nil {
		return nil
	}
	out := new(AdverseSituation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdverseSituation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdverseSituationAgentRunResponderSpec) DeepCopyInto(out *AdverseSituationAgentRunResponderSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ProfileRef != nil {
		in, out := &in.ProfileRef, &out.ProfileRef
		*out = new(NamespacedObjectReference)
		**out = **in
	}
	if in.HarnessProfileRef != nil {
		in, out := &in.HarnessProfileRef, &out.HarnessProfileRef
		*out = new(NamespacedObjectReference)
		**out = **in
	}
	if in.SkillSets != nil {
		in, out := &in.SkillSets, &out.SkillSets
		*out = new(AgentSkillCompositionSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Harness.DeepCopyInto(&out.Harness)
	in.Scope.DeepCopyInto(&out.Scope)
	if in.Docs != nil {
		in, out := &in.Docs, &out.Docs
		*out = new(AgentRunDocsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.IssueTracking != nil {
		in, out := &in.IssueTracking, &out.IssueTracking
		*out = new(AgentRunIssueTrackingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = new(AgentRunNotificationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdverseSituationAgentRunResponderSpec.
func (in *AdverseSituationAgentRunResponderSpec) DeepCopy() *AdverseSituationAgentRunResponderSpec {
	if in == nil {
		return nil
	}
	out := new(AdverseSituationAgentRunResponderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdverseSituationBufferSpec) DeepCopyInto(out *AdverseSituationBufferSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdverseSituationBufferSpec.
func (in *AdverseSituationBufferSpec) DeepCopy() *AdverseSituationBufferSpec {
	if in == nil {
		return nil
	}
	out := new(AdverseSituationBufferSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdverseSituationEvent) DeepCopyInto(out *AdverseSituationEvent) {
	*out = *in
	out.SourceRef = in.SourceRef
	if in.FirstSeenAt != nil {
		in, out := &in.FirstSeenAt, &out.FirstSeenAt
		*out = (*in).DeepCopy()
	}
	if in.LastSeenAt != nil {
		in, out := &in.LastSeenAt, &out.LastSeenAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdverseSituationEvent.
func (in *AdverseSituationEvent) DeepCopy() *AdverseSituationEvent {
	if in == nil {
		return nil
	}
	out := new(AdverseSituationEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdverseSituationList) DeepCopyInto(out *AdverseSituationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AdverseSituation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdverseSituationList.
func (in *AdverseSituationList) DeepCopy() *AdverseSituationList {
	if in == nil {
		return nil
	}
	out := new(AdverseSituationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdverseSituationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdverseSituationRespondersSpec) DeepCopyInto(out *AdverseSituationRespondersSpec) {
	*out = *in
	if in.AgentRun != nil {
		in, out := &in.AgentRun, &out.AgentRun
		*out = new(AdverseSituationAgentRunResponderSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdverseSituationRespondersSpec.
func (in *AdverseSituationRespondersSpec) DeepCopy() *AdverseSituationRespondersSpec {
	if in == nil {
		return nil
	}
	out := new(AdverseSituationRespondersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdverseSituationSpec) DeepCopyInto(out *AdverseSituationSpec) {
	*out = *in
	out.Buffer = in.Buffer
	in.Responders.DeepCopyInto(&out.Responders)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdverseSituationSpec.
func (in *AdverseSituationSpec) DeepCopy() *AdverseSituationSpec {
	if in == nil {
		return nil
	}
	out := new(AdverseSituationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdverseSituationStatus) DeepCopyInto(out *AdverseSituationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]AdverseSituationEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastEventAt != nil {
		in, out := &in.LastEventAt, &out.LastEventAt
		*out = (*in).DeepCopy()
	}
	if in.QuietUntil != nil {
		in, out := &in.QuietUntil, &out.QuietUntil
		*out = (*in).DeepCopy()
	}
	if in.ResolvedAt != nil {
		in, out := &in.ResolvedAt, &out.ResolvedAt
		*out = (*in).DeepCopy()
	}
	if in.PullRequestObservedAt != nil {
		in, out := &in.PullRequestObservedAt, &out.PullRequestObservedAt
		*out = (*in).DeepCopy()
	}
	if in.PullRequestQuietUntil != nil {
		in, out := &in.PullRequestQuietUntil, &out.PullRequestQuietUntil
		*out = (*in).DeepCopy()
	}
	if in.ActiveResponderRef != nil {
		in, out := &in.ActiveResponderRef, &out.ActiveResponderRef
		*out = new(NamespacedObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdverseSituationStatus.
func (in *AdverseSituationStatus) DeepCopy() *AdverseSituationStatus {
	if in == nil {
		return nil
	}
	out := new(AdverseSituationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentDataVolume) DeepCopyInto(out *AgentDataVolume) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentDataVolume.
func (in *AgentDataVolume) DeepCopy() *AgentDataVolume {
	if in == nil {
		return nil
	}
	out := new(AgentDataVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentDataVolume) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentDataVolumeList) DeepCopyInto(out *AgentDataVolumeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentDataVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentDataVolumeList.
func (in *AgentDataVolumeList) DeepCopy() *AgentDataVolumeList {
	if in == nil {
		return nil
	}
	out := new(AgentDataVolumeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentDataVolumeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentDataVolumeSpec) DeepCopyInto(out *AgentDataVolumeSpec) {
	*out = *in
	if in.ApplicationRef != nil {
		in, out := &in.ApplicationRef, &out.ApplicationRef
		*out = new(ApplicationReferenceSpec)
		**out = **in
	}
	if in.ProfileRef != nil {
		in, out := &in.ProfileRef, &out.ProfileRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	out.Size = in.Size.DeepCopy()
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]corev1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ExtraEnv != nil {
		in, out := &in.ExtraEnv, &out.ExtraEnv
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExternalSync != nil {
		in, out := &in.ExternalSync, &out.ExternalSync
		*out = new(ExternalVolumeSyncSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentDataVolumeSpec.
func (in *AgentDataVolumeSpec) DeepCopy() *AgentDataVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(AgentDataVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentDataVolumeStatus) DeepCopyInto(out *AgentDataVolumeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProfileRef != nil {
		in, out := &in.ProfileRef, &out.ProfileRef
		*out = new(NamespacedObjectReference)
		**out = **in
	}
	if in.ClaimRef != nil {
		in, out := &in.ClaimRef, &out.ClaimRef
		*out = new(NamespacedObjectReference)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ExtraEnv != nil {
		in, out := &in.ExtraEnv, &out.ExtraEnv
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExternalSync != nil {
		in, out := &in.ExternalSync, &out.ExternalSync
		*out = new(ExternalVolumeSyncStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentDataVolumeStatus.
func (in *AgentDataVolumeStatus) DeepCopy() *AgentDataVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(AgentDataVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessProfile) DeepCopyInto(out *AgentHarnessProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessProfile.
func (in *AgentHarnessProfile) DeepCopy() *AgentHarnessProfile {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentHarnessProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessProfileList) DeepCopyInto(out *AgentHarnessProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentHarnessProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessProfileList.
func (in *AgentHarnessProfileList) DeepCopy() *AgentHarnessProfileList {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentHarnessProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHarnessProfileSpec) DeepCopyInto(out *AgentHarnessProfileSpec) {
	*out = *in
	in.Backend.DeepCopyInto(&out.Backend)
	in.Execution.DeepCopyInto(&out.Execution)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHarnessProfileSpec.
func (in *AgentHarnessProfileSpec) DeepCopy() *AgentHarnessProfileSpec {
	if in == nil {
		return nil
	}
	out := new(AgentHarnessProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRun) DeepCopyInto(out *AgentRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRun.
func (in *AgentRun) DeepCopy() *AgentRun {
	if in == nil {
		return nil
	}
	out := new(AgentRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunArchiveStatus) DeepCopyInto(out *AgentRunArchiveStatus) {
	*out = *in
	if in.ArchivedAt != nil {
		in, out := &in.ArchivedAt, &out.ArchivedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunArchiveStatus.
func (in *AgentRunArchiveStatus) DeepCopy() *AgentRunArchiveStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRunArchiveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunCodexBackendSpec) DeepCopyInto(out *AgentRunCodexBackendSpec) {
	*out = *in
	if in.AdditionalArgs != nil {
		in, out := &in.AdditionalArgs, &out.AdditionalArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunCodexBackendSpec.
func (in *AgentRunCodexBackendSpec) DeepCopy() *AgentRunCodexBackendSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunCodexBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunControl) DeepCopyInto(out *AgentRunControl) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunControl.
func (in *AgentRunControl) DeepCopy() *AgentRunControl {
	if in == nil {
		return nil
	}
	out := new(AgentRunControl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRunControl) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunControlList) DeepCopyInto(out *AgentRunControlList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentRunControl, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunControlList.
func (in *AgentRunControlList) DeepCopy() *AgentRunControlList {
	if in == nil {
		return nil
	}
	out := new(AgentRunControlList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRunControlList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunControlSourceSpec) DeepCopyInto(out *AgentRunControlSourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunControlSourceSpec.
func (in *AgentRunControlSourceSpec) DeepCopy() *AgentRunControlSourceSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunControlSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunControlSpec) DeepCopyInto(out *AgentRunControlSpec) {
	*out = *in
	out.ApplicationRef = in.ApplicationRef
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(AgentRunControlSourceSpec)
		**out = **in
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunControlSpec.
func (in *AgentRunControlSpec) DeepCopy() *AgentRunControlSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunControlSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunControlStatus) DeepCopyInto(out *AgentRunControlStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunControlStatus.
func (in *AgentRunControlStatus) DeepCopy() *AgentRunControlStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRunControlStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunCustomBackendSpec) DeepCopyInto(out *AgentRunCustomBackendSpec) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunCustomBackendSpec.
func (in *AgentRunCustomBackendSpec) DeepCopy() *AgentRunCustomBackendSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunCustomBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunDataVolumeRef) DeepCopyInto(out *AgentRunDataVolumeRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunDataVolumeRef.
func (in *AgentRunDataVolumeRef) DeepCopy() *AgentRunDataVolumeRef {
	if in == nil {
		return nil
	}
	out := new(AgentRunDataVolumeRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunDataVolumeStatus) DeepCopyInto(out *AgentRunDataVolumeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunDataVolumeStatus.
func (in *AgentRunDataVolumeStatus) DeepCopy() *AgentRunDataVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRunDataVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunDecisionStatus) DeepCopyInto(out *AgentRunDecisionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunDecisionStatus.
func (in *AgentRunDecisionStatus) DeepCopy() *AgentRunDecisionStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRunDecisionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunDiscordNotificationSpec) DeepCopyInto(out *AgentRunDiscordNotificationSpec) {
	*out = *in
	out.WebhookURLRef = in.WebhookURLRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunDiscordNotificationSpec.
func (in *AgentRunDiscordNotificationSpec) DeepCopy() *AgentRunDiscordNotificationSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunDiscordNotificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunDocsSpec) DeepCopyInto(out *AgentRunDocsSpec) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RuntimePaths != nil {
		in, out := &in.RuntimePaths, &out.RuntimePaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunDocsSpec.
func (in *AgentRunDocsSpec) DeepCopy() *AgentRunDocsSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunDocsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunExternalSecretRefreshRef) DeepCopyInto(out *AgentRunExternalSecretRefreshRef) {
	*out = *in
	out.TargetSecretRef = in.TargetSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunExternalSecretRefreshRef.
func (in *AgentRunExternalSecretRefreshRef) DeepCopy() *AgentRunExternalSecretRefreshRef {
	if in == nil {
		return nil
	}
	out := new(AgentRunExternalSecretRefreshRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunExternalSecretRefreshStatus) DeepCopyInto(out *AgentRunExternalSecretRefreshStatus) {
	*out = *in
	if in.RequestedAt != nil {
		in, out := &in.RequestedAt, &out.RequestedAt
		*out = (*in).DeepCopy()
	}
	if in.PreviousRefreshTime != nil {
		in, out := &in.PreviousRefreshTime, &out.PreviousRefreshTime
		*out = (*in).DeepCopy()
	}
	if in.RefreshedAt != nil {
		in, out := &in.RefreshedAt, &out.RefreshedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunExternalSecretRefreshStatus.
func (in *AgentRunExternalSecretRefreshStatus) DeepCopy() *AgentRunExternalSecretRefreshStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRunExternalSecretRefreshStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunGitHubSkillSourceSpec) DeepCopyInto(out *AgentRunGitHubSkillSourceSpec) {
	*out = *in
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunGitHubSkillSourceSpec.
func (in *AgentRunGitHubSkillSourceSpec) DeepCopy() *AgentRunGitHubSkillSourceSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunGitHubSkillSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunGrokBuildBackendSpec) DeepCopyInto(out *AgentRunGrokBuildBackendSpec) {
	*out = *in
	if in.AdditionalArgs != nil {
		in, out := &in.AdditionalArgs, &out.AdditionalArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunGrokBuildBackendSpec.
func (in *AgentRunGrokBuildBackendSpec) DeepCopy() *AgentRunGrokBuildBackendSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunGrokBuildBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunHarnessBackendSpec) DeepCopyInto(out *AgentRunHarnessBackendSpec) {
	*out = *in
	if in.Codex != nil {
		in, out := &in.Codex, &out.Codex
		*out = new(AgentRunCodexBackendSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HermesAgent != nil {
		in, out := &in.HermesAgent, &out.HermesAgent
		*out = new(AgentRunHermesBackendSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OpenClaw != nil {
		in, out := &in.OpenClaw, &out.OpenClaw
		*out = new(AgentRunOpenClawBackendSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GrokBuild != nil {
		in, out := &in.GrokBuild, &out.GrokBuild
		*out = new(AgentRunGrokBuildBackendSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PiAgent != nil {
		in, out := &in.PiAgent, &out.PiAgent
		*out = new(AgentRunPiBackendSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = new(AgentRunCustomBackendSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunHarnessBackendSpec.
func (in *AgentRunHarnessBackendSpec) DeepCopy() *AgentRunHarnessBackendSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunHarnessBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunHarnessExecutionSpec) DeepCopyInto(out *AgentRunHarnessExecutionSpec) {
	*out = *in
	if in.EnvSecretRefs != nil {
		in, out := &in.EnvSecretRefs, &out.EnvSecretRefs
		*out = make([]NamespacedObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.ExternalSecretRefreshRefs != nil {
		in, out := &in.ExternalSecretRefreshRefs, &out.ExternalSecretRefreshRefs
		*out = make([]AgentRunExternalSecretRefreshRef, len(*in))
		copy(*out, *in)
	}
	if in.ExtraEnv != nil {
		in, out := &in.ExtraEnv, &out.ExtraEnv
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DataVolumeRefs != nil {
		in, out := &in.DataVolumeRefs, &out.DataVolumeRefs
		*out = make([]AgentRunDataVolumeRef, len(*in))
		copy(*out, *in)
	}
	out.SpiffeWorkloadAPI = in.SpiffeWorkloadAPI
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunHarnessExecutionSpec.
func (in *AgentRunHarnessExecutionSpec) DeepCopy() *AgentRunHarnessExecutionSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunHarnessExecutionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunHarnessSpec) DeepCopyInto(out *AgentRunHarnessSpec) {
	*out = *in
	in.Backend.DeepCopyInto(&out.Backend)
	in.Execution.DeepCopyInto(&out.Execution)
	if in.SkillInjections != nil {
		in, out := &in.SkillInjections, &out.SkillInjections
		*out = make([]AgentRunSkillInjectionSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Subagents != nil {
		in, out := &in.Subagents, &out.Subagents
		*out = make([]AgentRunSubagentSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]AgentRunToolSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunHarnessSpec.
func (in *AgentRunHarnessSpec) DeepCopy() *AgentRunHarnessSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunHarnessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunHermesBackendSpec) DeepCopyInto(out *AgentRunHermesBackendSpec) {
	*out = *in
	if in.AdditionalArgs != nil {
		in, out := &in.AdditionalArgs, &out.AdditionalArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunHermesBackendSpec.
func (in *AgentRunHermesBackendSpec) DeepCopy() *AgentRunHermesBackendSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunHermesBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunIssueRef) DeepCopyInto(out *AgentRunIssueRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunIssueRef.
func (in *AgentRunIssueRef) DeepCopy() *AgentRunIssueRef {
	if in == nil {
		return nil
	}
	out := new(AgentRunIssueRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunIssueTrackingSpec) DeepCopyInto(out *AgentRunIssueTrackingSpec) {
	*out = *in
	if in.Issues != nil {
		in, out := &in.Issues, &out.Issues
		*out = make([]AgentRunIssueRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunIssueTrackingSpec.
func (in *AgentRunIssueTrackingSpec) DeepCopy() *AgentRunIssueTrackingSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunIssueTrackingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunList) DeepCopyInto(out *AgentRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunList.
func (in *AgentRunList) DeepCopy() *AgentRunList {
	if in == nil {
		return nil
	}
	out := new(AgentRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunNotificationSpec) DeepCopyInto(out *AgentRunNotificationSpec) {
	*out = *in
	if in.Telegram != nil {
		in, out := &in.Telegram, &out.Telegram
		*out = new(AgentRunTelegramNotificationSpec)
		**out = **in
	}
	if in.Discord != nil {
		in, out := &in.Discord, &out.Discord
		*out = new(AgentRunDiscordNotificationSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunNotificationSpec.
func (in *AgentRunNotificationSpec) DeepCopy() *AgentRunNotificationSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunNotificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunOpenClawBackendSpec) DeepCopyInto(out *AgentRunOpenClawBackendSpec) {
	*out = *in
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(bool)
		**out = **in
	}
	if in.AdditionalArgs != nil {
		in, out := &in.AdditionalArgs, &out.AdditionalArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunOpenClawBackendSpec.
func (in *AgentRunOpenClawBackendSpec) DeepCopy() *AgentRunOpenClawBackendSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunOpenClawBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunPiBackendSpec) DeepCopyInto(out *AgentRunPiBackendSpec) {
	*out = *in
	if in.AdditionalArgs != nil {
		in, out := &in.AdditionalArgs, &out.AdditionalArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunPiBackendSpec.
func (in *AgentRunPiBackendSpec) DeepCopy() *AgentRunPiBackendSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunPiBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunProfile) DeepCopyInto(out *AgentRunProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunProfile.
func (in *AgentRunProfile) DeepCopy() *AgentRunProfile {
	if in == nil {
		return nil
	}
	out := new(AgentRunProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRunProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunProfileList) DeepCopyInto(out *AgentRunProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentRunProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunProfileList.
func (in *AgentRunProfileList) DeepCopy() *AgentRunProfileList {
	if in == nil {
		return nil
	}
	out := new(AgentRunProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentRunProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunProfileSpec) DeepCopyInto(out *AgentRunProfileSpec) {
	*out = *in
	in.Scope.DeepCopyInto(&out.Scope)
	if in.Docs != nil {
		in, out := &in.Docs, &out.Docs
		*out = new(AgentRunDocsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.IssueTracking != nil {
		in, out := &in.IssueTracking, &out.IssueTracking
		*out = new(AgentRunIssueTrackingSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Harness.DeepCopyInto(&out.Harness)
	if in.HarnessProfileRef != nil {
		in, out := &in.HarnessProfileRef, &out.HarnessProfileRef
		*out = new(NamespacedObjectReference)
		**out = **in
	}
	if in.SkillSets != nil {
		in, out := &in.SkillSets, &out.SkillSets
		*out = new(AgentSkillCompositionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = new(AgentRunNotificationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunProfileSpec.
func (in *AgentRunProfileSpec) DeepCopy() *AgentRunProfileSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunResolvedCompositionStatus) DeepCopyInto(out *AgentRunResolvedCompositionStatus) {
	*out = *in
	if in.ResolvedAt != nil {
		in, out := &in.ResolvedAt, &out.ResolvedAt
		*out = (*in).DeepCopy()
	}
	if in.ProfileRef != nil {
		in, out := &in.ProfileRef, &out.ProfileRef
		*out = new(AgentRunResolvedObjectReferenceStatus)
		**out = **in
	}
	if in.HarnessProfileRef != nil {
		in, out := &in.HarnessProfileRef, &out.HarnessProfileRef
		*out = new(AgentRunResolvedObjectReferenceStatus)
		**out = **in
	}
	if in.SkillSetRefs != nil {
		in, out := &in.SkillSetRefs, &out.SkillSetRefs
		*out = make([]AgentRunResolvedObjectReferenceStatus, len(*in))
		copy(*out, *in)
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(AgentRunResolvedScopeStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunResolvedCompositionStatus.
func (in *AgentRunResolvedCompositionStatus) DeepCopy() *AgentRunResolvedCompositionStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRunResolvedCompositionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunResolvedObjectReferenceStatus) DeepCopyInto(out *AgentRunResolvedObjectReferenceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunResolvedObjectReferenceStatus.
func (in *AgentRunResolvedObjectReferenceStatus) DeepCopy() *AgentRunResolvedObjectReferenceStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRunResolvedObjectReferenceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunResolvedScopeStatus) DeepCopyInto(out *AgentRunResolvedScopeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunResolvedScopeStatus.
func (in *AgentRunResolvedScopeStatus) DeepCopy() *AgentRunResolvedScopeStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRunResolvedScopeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunScopeSpec) DeepCopyInto(out *AgentRunScopeSpec) {
	*out = *in
	if in.ApplicationRef != nil {
		in, out := &in.ApplicationRef, &out.ApplicationRef
		*out = new(ApplicationReferenceSpec)
		**out = **in
	}
	if in.ApplicationTargetRef != nil {
		in, out := &in.ApplicationTargetRef, &out.ApplicationTargetRef
		*out = new(ApplicationTargetReferenceSpec)
		**out = **in
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResourceKinds != nil {
		in, out := &in.ResourceKinds, &out.ResourceKinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunScopeSpec.
func (in *AgentRunScopeSpec) DeepCopy() *AgentRunScopeSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunScopeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunSkillInjectionSpec) DeepCopyInto(out *AgentRunSkillInjectionSpec) {
	*out = *in
	if in.SourceRefs != nil {
		in, out := &in.SourceRefs, &out.SourceRefs
		*out = make([]AgentRunSkillSourceRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunSkillInjectionSpec.
func (in *AgentRunSkillInjectionSpec) DeepCopy() *AgentRunSkillInjectionSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunSkillInjectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunSkillSourceRef) DeepCopyInto(out *AgentRunSkillSourceRef) {
	*out = *in
	if in.GitHub != nil {
		in, out := &in.GitHub, &out.GitHub
		*out = new(AgentRunGitHubSkillSourceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunSkillSourceRef.
func (in *AgentRunSkillSourceRef) DeepCopy() *AgentRunSkillSourceRef {
	if in == nil {
		return nil
	}
	out := new(AgentRunSkillSourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunSourceRef) DeepCopyInto(out *AgentRunSourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunSourceRef.
func (in *AgentRunSourceRef) DeepCopy() *AgentRunSourceRef {
	if in == nil {
		return nil
	}
	out := new(AgentRunSourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunSpec) DeepCopyInto(out *AgentRunSpec) {
	*out = *in
	out.SourceRef = in.SourceRef
	in.Trigger.DeepCopyInto(&out.Trigger)
	if in.ProfileRef != nil {
		in, out := &in.ProfileRef, &out.ProfileRef
		*out = new(NamespacedObjectReference)
		**out = **in
	}
	if in.HarnessProfileRef != nil {
		in, out := &in.HarnessProfileRef, &out.HarnessProfileRef
		*out = new(NamespacedObjectReference)
		**out = **in
	}
	if in.SkillSets != nil {
		in, out := &in.SkillSets, &out.SkillSets
		*out = new(AgentSkillCompositionSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Scope.DeepCopyInto(&out.Scope)
	if in.Docs != nil {
		in, out := &in.Docs, &out.Docs
		*out = new(AgentRunDocsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.IssueTracking != nil {
		in, out := &in.IssueTracking, &out.IssueTracking
		*out = new(AgentRunIssueTrackingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ScheduleRef != nil {
		in, out := &in.ScheduleRef, &out.ScheduleRef
		*out = new(NamespacedObjectReference)
		**out = **in
	}
	if in.SituationRef != nil {
		in, out := &in.SituationRef, &out.SituationRef
		*out = new(NamespacedObjectReference)
		**out = **in
	}
	in.Harness.DeepCopyInto(&out.Harness)
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = new(AgentRunNotificationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunSpec.
func (in *AgentRunSpec) DeepCopy() *AgentRunSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunSpiffeWorkloadAPISpec) DeepCopyInto(out *AgentRunSpiffeWorkloadAPISpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunSpiffeWorkloadAPISpec.
func (in *AgentRunSpiffeWorkloadAPISpec) DeepCopy() *AgentRunSpiffeWorkloadAPISpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunSpiffeWorkloadAPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunStatus) DeepCopyInto(out *AgentRunStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.JobRef != nil {
		in, out := &in.JobRef, &out.JobRef
		*out = new(NamespacedObjectReference)
		**out = **in
	}
	if in.RunnerPodRef != nil {
		in, out := &in.RunnerPodRef, &out.RunnerPodRef
		*out = new(NamespacedObjectReference)
		**out = **in
	}
	if in.DataVolumes != nil {
		in, out := &in.DataVolumes, &out.DataVolumes
		*out = make([]AgentRunDataVolumeStatus, len(*in))
		copy(*out, *in)
	}
	if in.ExternalSecretRefreshes != nil {
		in, out := &in.ExternalSecretRefreshes, &out.ExternalSecretRefreshes
		*out = make([]AgentRunExternalSecretRefreshStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Archive != nil {
		in, out := &in.Archive, &out.Archive
		*out = new(AgentRunArchiveStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ResolvedComposition != nil {
		in, out := &in.ResolvedComposition, &out.ResolvedComposition
		*out = new(AgentRunResolvedCompositionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Decision != nil {
		in, out := &in.Decision, &out.Decision
		*out = new(AgentRunDecisionStatus)
		**out = **in
	}
	if in.Reports != nil {
		in, out := &in.Reports, &out.Reports
		*out = make([]AgentRunStatusReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Result.DeepCopyInto(&out.Result)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunStatus.
func (in *AgentRunStatus) DeepCopy() *AgentRunStatus {
	if in == nil {
		return nil
	}
	out := new(AgentRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunStatusReport) DeepCopyInto(out *AgentRunStatusReport) {
	*out = *in
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunStatusReport.
func (in *AgentRunStatusReport) DeepCopy() *AgentRunStatusReport {
	if in == nil {
		return nil
	}
	out := new(AgentRunStatusReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunSubagentSpec) DeepCopyInto(out *AgentRunSubagentSpec) {
	*out = *in
	if in.ToolNames != nil {
		in, out := &in.ToolNames, &out.ToolNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunSubagentSpec.
func (in *AgentRunSubagentSpec) DeepCopy() *AgentRunSubagentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunSubagentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunTelegramNotificationSpec) DeepCopyInto(out *AgentRunTelegramNotificationSpec) {
	*out = *in
	out.BotTokenRef = in.BotTokenRef
	out.ChatIDRef = in.ChatIDRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunTelegramNotificationSpec.
func (in *AgentRunTelegramNotificationSpec) DeepCopy() *AgentRunTelegramNotificationSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunTelegramNotificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunToolSpec) DeepCopyInto(out *AgentRunToolSpec) {
	*out = *in
	if in.VerifyCommand != nil {
		in, out := &in.VerifyCommand, &out.VerifyCommand
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunToolSpec.
func (in *AgentRunToolSpec) DeepCopy() *AgentRunToolSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRunToolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRunTriggerSnapshot) DeepCopyInto(out *AgentRunTriggerSnapshot) {
	*out = *in
	if in.DetectedAt != nil {
		in, out := &in.DetectedAt, &out.DetectedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRunTriggerSnapshot.
func (in *AgentRunTriggerSnapshot) DeepCopy() *AgentRunTriggerSnapshot {
	if in == nil {
		return nil
	}
	out := new(AgentRunTriggerSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSchedule) DeepCopyInto(out *AgentSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSchedule.
func (in *AgentSchedule) DeepCopy() *AgentSchedule {
	if in == nil {
		return nil
	}
	out := new(AgentSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentScheduleBackoffSpec) DeepCopyInto(out *AgentScheduleBackoffSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentScheduleBackoffSpec.
func (in *AgentScheduleBackoffSpec) DeepCopy() *AgentScheduleBackoffSpec {
	if in == nil {
		return nil
	}
	out := new(AgentScheduleBackoffSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentScheduleList) DeepCopyInto(out *AgentScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentScheduleList.
func (in *AgentScheduleList) DeepCopy() *AgentScheduleList {
	if in == nil {
		return nil
	}
	out := new(AgentScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentScheduleRunTemplateSpec) DeepCopyInto(out *AgentScheduleRunTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentScheduleRunTemplateSpec.
func (in *AgentScheduleRunTemplateSpec) DeepCopy() *AgentScheduleRunTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(AgentScheduleRunTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentScheduleSpec) DeepCopyInto(out *AgentScheduleSpec) {
	*out = *in
	if in.ApplicationRef != nil {
		in, out := &in.ApplicationRef, &out.ApplicationRef
		*out = new(ApplicationReferenceSpec)
		**out = **in
	}
	if in.Backoff != nil {
		in, out := &in.Backoff, &out.Backoff
		*out = new(AgentScheduleBackoffSpec)
		**out = **in
	}
	in.RunTemplate.DeepCopyInto(&out.RunTemplate)
	if in.RunTemplates != nil {
		in, out := &in.RunTemplates, &out.RunTemplates
		*out = make([]AgentScheduleRunTemplateSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentScheduleSpec.
func (in *AgentScheduleSpec) DeepCopy() *AgentScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(AgentScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentScheduleStatus) DeepCopyInto(out *AgentScheduleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastRunAt != nil {
		in, out := &in.LastRunAt, &out.LastRunAt
		*out = (*in).DeepCopy()
	}
	if in.NextRunAt != nil {
		in, out := &in.NextRunAt, &out.NextRunAt
		*out = (*in).DeepCopy()
	}
	if in.ActiveRunRef != nil {
		in, out := &in.ActiveRunRef, &out.ActiveRunRef
		*out = new(NamespacedObjectReference)
		**out = **in
	}
	if in.LastRunRef != nil {
		in, out := &in.LastRunRef, &out.LastRunRef
		*out = new(NamespacedObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentScheduleStatus.
func (in *AgentScheduleStatus) DeepCopy() *AgentScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(AgentScheduleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSkillCompositionSpec) DeepCopyInto(out *AgentSkillCompositionSpec) {
	*out = *in
	if in.Refs != nil {
		in, out := &in.Refs, &out.Refs
		*out = make([]NamespacedObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = make([]AgentSkillOverrideSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSkillCompositionSpec.
func (in *AgentSkillCompositionSpec) DeepCopy() *AgentSkillCompositionSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSkillCompositionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSkillOverrideSpec) DeepCopyInto(out *AgentSkillOverrideSpec) {
	*out = *in
	if in.SourceRefs != nil {
		in, out := &in.SourceRefs, &out.SourceRefs
		*out = make([]AgentRunSkillSourceRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSkillOverrideSpec.
func (in *AgentSkillOverrideSpec) DeepCopy() *AgentSkillOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSkillOverrideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSkillSet) DeepCopyInto(out *AgentSkillSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSkillSet.
func (in *AgentSkillSet) DeepCopy() *AgentSkillSet {
	if in == nil {
		return nil
	}
	out := new(AgentSkillSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentSkillSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSkillSetList) DeepCopyInto(out *AgentSkillSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentSkillSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSkillSetList.
func (in *AgentSkillSetList) DeepCopy() *AgentSkillSetList {
	if in == nil {
		return nil
	}
	out := new(AgentSkillSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentSkillSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSkillSetSpec) DeepCopyInto(out *AgentSkillSetSpec) {
	*out = *in
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = make([]AgentRunSkillInjectionSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]AgentRunToolSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Subagents != nil {
		in, out := &in.Subagents, &out.Subagents
		*out = make([]AgentRunSubagentSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSkillSetSpec.
func (in *AgentSkillSetSpec) DeepCopy() *AgentSkillSetSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSkillSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationReferenceSpec) DeepCopyInto(out *ApplicationReferenceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationReferenceSpec.
func (in *ApplicationReferenceSpec) DeepCopy() *ApplicationReferenceSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationReferenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationTargetReferenceSpec) DeepCopyInto(out *ApplicationTargetReferenceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationTargetReferenceSpec.
func (in *ApplicationTargetReferenceSpec) DeepCopy() *ApplicationTargetReferenceSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationTargetReferenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalVolumeSyncS3Spec) DeepCopyInto(out *ExternalVolumeSyncS3Spec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalVolumeSyncS3Spec.
func (in *ExternalVolumeSyncS3Spec) DeepCopy() *ExternalVolumeSyncS3Spec {
	if in == nil {
		return nil
	}
	out := new(ExternalVolumeSyncS3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalVolumeSyncSpec) DeepCopyInto(out *ExternalVolumeSyncSpec) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(ExternalVolumeSyncS3Spec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalVolumeSyncSpec.
func (in *ExternalVolumeSyncSpec) DeepCopy() *ExternalVolumeSyncSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalVolumeSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalVolumeSyncStatus) DeepCopyInto(out *ExternalVolumeSyncStatus) {
	*out = *in
	if in.LastAttemptTime != nil {
		in, out := &in.LastAttemptTime, &out.LastAttemptTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessTime != nil {
		in, out := &in.LastSuccessTime, &out.LastSuccessTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalVolumeSyncStatus.
func (in *ExternalVolumeSyncStatus) DeepCopy() *ExternalVolumeSyncStatus {
	if in == nil {
		return nil
	}
	out := new(ExternalVolumeSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedObjectReference) DeepCopyInto(out *NamespacedObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedObjectReference.
func (in *NamespacedObjectReference) DeepCopy() *NamespacedObjectReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeProfile) DeepCopyInto(out *VolumeProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeProfile.
func (in *VolumeProfile) DeepCopy() *VolumeProfile {
	if in == nil {
		return nil
	}
	out := new(VolumeProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolumeProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeProfileCapacityPolicySpec) DeepCopyInto(out *VolumeProfileCapacityPolicySpec) {
	*out = *in
	if in.MaxNodeAllocatableEphemeralStoragePercent != nil {
		in, out := &in.MaxNodeAllocatableEphemeralStoragePercent, &out.MaxNodeAllocatableEphemeralStoragePercent
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeProfileCapacityPolicySpec.
func (in *VolumeProfileCapacityPolicySpec) DeepCopy() *VolumeProfileCapacityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(VolumeProfileCapacityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeProfileList) DeepCopyInto(out *VolumeProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VolumeProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeProfileList.
func (in *VolumeProfileList) DeepCopy() *VolumeProfileList {
	if in == nil {
		return nil
	}
	out := new(VolumeProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolumeProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeProfileSpec) DeepCopyInto(out *VolumeProfileSpec) {
	*out = *in
	if in.ApplicationRef != nil {
		in, out := &in.ApplicationRef, &out.ApplicationRef
		*out = new(ApplicationReferenceSpec)
		**out = **in
	}
	if in.CapacityPolicy != nil {
		in, out := &in.CapacityPolicy, &out.CapacityPolicy
		*out = new(VolumeProfileCapacityPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]VolumeProfileVolumeSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeProfileSpec.
func (in *VolumeProfileSpec) DeepCopy() *VolumeProfileSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeProfileStatus) DeepCopyInto(out *VolumeProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]VolumeProfileVolumeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeProfileStatus.
func (in *VolumeProfileStatus) DeepCopy() *VolumeProfileStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeProfileVolumeSizeSpec) DeepCopyInto(out *VolumeProfileVolumeSizeSpec) {
	*out = *in
	out.Request = in.Request.DeepCopy()
	if in.MaxNodeAllocatableEphemeralStoragePercent != nil {
		in, out := &in.MaxNodeAllocatableEphemeralStoragePercent, &out.MaxNodeAllocatableEphemeralStoragePercent
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeProfileVolumeSizeSpec.
func (in *VolumeProfileVolumeSizeSpec) DeepCopy() *VolumeProfileVolumeSizeSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeProfileVolumeSizeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeProfileVolumeSpec) DeepCopyInto(out *VolumeProfileVolumeSpec) {
	*out = *in
	in.Size.DeepCopyInto(&out.Size)
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]corev1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ExtraEnv != nil {
		in, out := &in.ExtraEnv, &out.ExtraEnv
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExternalSync != nil {
		in, out := &in.ExternalSync, &out.ExternalSync
		*out = new(ExternalVolumeSyncSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeProfileVolumeSpec.
func (in *VolumeProfileVolumeSpec) DeepCopy() *VolumeProfileVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeProfileVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeProfileVolumeStatus) DeepCopyInto(out *VolumeProfileVolumeStatus) {
	*out = *in
	if in.ExternalSync != nil {
		in, out := &in.ExternalSync, &out.ExternalSync
		*out = new(ExternalVolumeSyncStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeProfileVolumeStatus.
func (in *VolumeProfileVolumeStatus) DeepCopy() *VolumeProfileVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeProfileVolumeStatus)
	in.DeepCopyInto(out)
	return out
}
